-- Manual Supabase production patch for Prisma drift after phone verification changes.
-- Paste this whole file into Supabase SQL Editor and run it once.
--
-- Safety rules:
-- - No DROP TABLE
-- - No database reset
-- - Only ADD COLUMN IF NOT EXISTS and CREATE TABLE IF NOT EXISTS
--
-- Local verification after applying the SQL:
-- npx prisma validate
-- npx prisma generate

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phoneVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phoneVerifiedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramId" BIGINT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "username" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramLinkCode" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "telegramLinkExpiresAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "businessId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "templateKey" TEXT NOT NULL DEFAULT 'custom';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "coverImageUrl" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "secondaryColor" TEXT NOT NULL DEFAULT '#FFFFFF';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "backgroundColor" TEXT NOT NULL DEFAULT '#F5F5F5';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "accentColor" TEXT NOT NULL DEFAULT '#3B82F6';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "telegramUrl" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "whatsappUrl" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "instagramUrl" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "telegramBotToken" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "telegramBotUsername" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "telegramUsername" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "telegramAdminChatId" BIGINT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'RUB';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "language" TEXT NOT NULL DEFAULT 'ru';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "timezone" TEXT NOT NULL DEFAULT 'Europe/Moscow';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "subscriptionPlanId" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "subscriptionStartDate" TIMESTAMP(3);
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "subscriptionEndDate" TIMESTAMP(3);
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "modulesEnabled" TEXT NOT NULL DEFAULT 'catalog,cart,profile';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "aiProvider" TEXT DEFAULT 'mock';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "aiModel" TEXT;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "aiEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "aiDailyLimit" INTEGER DEFAULT 10;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "aiMonthlyLimit" INTEGER DEFAULT 300;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "isDemo" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "ownerId" TEXT;

-- Products and services are stored in Prisma model "Item"; there is no separate "Product" table.
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "oldPrice" DOUBLE PRECISION;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "durationMinutes" INTEGER;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "stock" INTEGER;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "isAvailable" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "isPopular" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Item" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "totalPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "comment" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "internalNotes" TEXT;

ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "comment" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "internalNotes" TEXT;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "reminderSent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Booking" ADD COLUMN IF NOT EXISTS "reminderSentAt" TIMESTAMP(3);

ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "userId" TEXT;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "phoneVerified" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "verificationMethod" TEXT NOT NULL DEFAULT 'none';
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "totalOrders" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "totalSpent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "bonusBalance" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "SubscriptionPlan" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "SubscriptionPlan" ADD COLUMN IF NOT EXISTS "maxItems" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "SubscriptionPlan" ADD COLUMN IF NOT EXISTS "maxOrdersPerMonth" INTEGER NOT NULL DEFAULT 200;
ALTER TABLE "SubscriptionPlan" ADD COLUMN IF NOT EXISTS "maxStaff" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "SubscriptionPlan" ADD COLUMN IF NOT EXISTS "features" TEXT NOT NULL DEFAULT '[]';
ALTER TABLE "SubscriptionPlan" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS "PhoneVerification" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "customerId" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "codeHash" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "provider" TEXT NOT NULL,
  "expiresAt" TIMESTAMP(3) NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
